apiVersion: v1
kind: Service
metadata:
  name: {PROJECT_NAME}
  namespace: {PROJECT_NAMESPACE}
  labels:
    app: {PROJECT_NAME}
spec:
  selector:
    app: {PROJECT_NAME}
  ports:
    - port: {PROJECT_PORT}
      targetPort: {PROJECT_PORT}
      name: {PROJECT_NAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {PROJECT_NAME}
  namespace: {PROJECT_NAMESPACE}
  labels:
    app: {PROJECT_NAME}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {PROJECT_NAME}
  template:
    metadata:
      labels:
        app: {PROJECT_NAME}
    spec:
      containers:
        - name: {PROJECT_NAME}
          image: {PROJECT_IMAGE}
          ports:
            - containerPort: {PROJECT_PORT}
          env:
            - name: SERVER_PORT
              value: {PROJECT_PORT}
            - name: SERVER_NAME
              value: {PROJECT_NAME}
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef: # 这里是取eureka项目里定义的configMap里的值
                  name: eureka_host
                  key: registry_url
            - name: HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
