server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: ${SERVER_NAME:web-demo}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOST_NAME:localhost}