server:
  port: ${SERVER_PORT:8081}
spring:
  application:
    name: ${SERVER_NAME:web-demo}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    hostname: ${HOST_NAME:localhost}
    lease-renewal-interval-in-seconds: 5 # 续约间隔时间
    lease-expiration-duration-in-seconds: 10 # 服务失效时间
    prefer-ip-address: true # 开启服务IP注册，如果网关使用了Cloud-Gateway那么一定要增加该配置